# Generated by Django 3.0.7 on 2020-06-24 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200621_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='Direccion IP'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='vel_bajada',
            field=models.IntegerField(verbose_name='Velocidad de Descarga Kb'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='vel_subida',
            field=models.IntegerField(verbose_name='Velocidad de Subida Kb'),
        ),
    ]
