# Generated by Django 3.0.7 on 2020-06-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200624_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='cliente',
            new_name='nombre',
        ),
    ]
