# Generated by Django 3.0.7 on 2020-06-24 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200624_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='nombre',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
