# Generated by Django 3.0.7 on 2020-08-11 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200624_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
