# Generated by Django 3.0.7 on 2020-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200811_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='detalle',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='planes',
            name='detalle',
            field=models.TextField(max_length=160),
        ),
    ]
